# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brokerservice/protobuf/broker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='brokerservice/protobuf/broker.proto',
  package='com.google.cloud.broker.protobuf',
  syntax='proto3',
  serialized_options=_b('\n com.google.cloud.broker.protobufB\013BrokerProtoP\001'),
  serialized_pb=_b('\n#brokerservice/protobuf/broker.proto\x12 com.google.cloud.broker.protobuf\"W\n\x16GetSessionTokenRequest\x12\r\n\x05scope\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07renewer\x18\x04 \x01(\t\"0\n\x17GetSessionTokenResponse\x12\x15\n\rsession_token\x18\x01 \x01(\t\"1\n\x18RenewSessionTokenRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"/\n\x19RenewSessionTokenResponse\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\"2\n\x19\x43\x61ncelSessionTokenRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"\x1c\n\x1a\x43\x61ncelSessionTokenResponse\"E\n\x15GetAccessTokenRequest\x12\r\n\x05scope\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\"B\n\x16GetAccessTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\x32\xc0\x04\n\x06\x42roker\x12\x88\x01\n\x0fGetSessionToken\x12\x38.com.google.cloud.broker.protobuf.GetSessionTokenRequest\x1a\x39.com.google.cloud.broker.protobuf.GetSessionTokenResponse\"\x00\x12\x8e\x01\n\x11RenewSessionToken\x12:.com.google.cloud.broker.protobuf.RenewSessionTokenRequest\x1a;.com.google.cloud.broker.protobuf.RenewSessionTokenResponse\"\x00\x12\x91\x01\n\x12\x43\x61ncelSessionToken\x12;.com.google.cloud.broker.protobuf.CancelSessionTokenRequest\x1a<.com.google.cloud.broker.protobuf.CancelSessionTokenResponse\"\x00\x12\x85\x01\n\x0eGetAccessToken\x12\x37.com.google.cloud.broker.protobuf.GetAccessTokenRequest\x1a\x38.com.google.cloud.broker.protobuf.GetAccessTokenResponse\"\x00\x42\x31\n com.google.cloud.broker.protobufB\x0b\x42rokerProtoP\x01\x62\x06proto3')
)




_GETSESSIONTOKENREQUEST = _descriptor.Descriptor(
  name='GetSessionTokenRequest',
  full_name='com.google.cloud.broker.protobuf.GetSessionTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='com.google.cloud.broker.protobuf.GetSessionTokenRequest.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='com.google.cloud.broker.protobuf.GetSessionTokenRequest.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='com.google.cloud.broker.protobuf.GetSessionTokenRequest.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='renewer', full_name='com.google.cloud.broker.protobuf.GetSessionTokenRequest.renewer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=160,
)


_GETSESSIONTOKENRESPONSE = _descriptor.Descriptor(
  name='GetSessionTokenResponse',
  full_name='com.google.cloud.broker.protobuf.GetSessionTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_token', full_name='com.google.cloud.broker.protobuf.GetSessionTokenResponse.session_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=210,
)


_RENEWSESSIONTOKENREQUEST = _descriptor.Descriptor(
  name='RenewSessionTokenRequest',
  full_name='com.google.cloud.broker.protobuf.RenewSessionTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_token', full_name='com.google.cloud.broker.protobuf.RenewSessionTokenRequest.session_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=261,
)


_RENEWSESSIONTOKENRESPONSE = _descriptor.Descriptor(
  name='RenewSessionTokenResponse',
  full_name='com.google.cloud.broker.protobuf.RenewSessionTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expires_at', full_name='com.google.cloud.broker.protobuf.RenewSessionTokenResponse.expires_at', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=310,
)


_CANCELSESSIONTOKENREQUEST = _descriptor.Descriptor(
  name='CancelSessionTokenRequest',
  full_name='com.google.cloud.broker.protobuf.CancelSessionTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_token', full_name='com.google.cloud.broker.protobuf.CancelSessionTokenRequest.session_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=362,
)


_CANCELSESSIONTOKENRESPONSE = _descriptor.Descriptor(
  name='CancelSessionTokenResponse',
  full_name='com.google.cloud.broker.protobuf.CancelSessionTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=392,
)


_GETACCESSTOKENREQUEST = _descriptor.Descriptor(
  name='GetAccessTokenRequest',
  full_name='com.google.cloud.broker.protobuf.GetAccessTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='com.google.cloud.broker.protobuf.GetAccessTokenRequest.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='com.google.cloud.broker.protobuf.GetAccessTokenRequest.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='com.google.cloud.broker.protobuf.GetAccessTokenRequest.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=463,
)


_GETACCESSTOKENRESPONSE = _descriptor.Descriptor(
  name='GetAccessTokenResponse',
  full_name='com.google.cloud.broker.protobuf.GetAccessTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='com.google.cloud.broker.protobuf.GetAccessTokenResponse.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expires_at', full_name='com.google.cloud.broker.protobuf.GetAccessTokenResponse.expires_at', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=531,
)

DESCRIPTOR.message_types_by_name['GetSessionTokenRequest'] = _GETSESSIONTOKENREQUEST
DESCRIPTOR.message_types_by_name['GetSessionTokenResponse'] = _GETSESSIONTOKENRESPONSE
DESCRIPTOR.message_types_by_name['RenewSessionTokenRequest'] = _RENEWSESSIONTOKENREQUEST
DESCRIPTOR.message_types_by_name['RenewSessionTokenResponse'] = _RENEWSESSIONTOKENRESPONSE
DESCRIPTOR.message_types_by_name['CancelSessionTokenRequest'] = _CANCELSESSIONTOKENREQUEST
DESCRIPTOR.message_types_by_name['CancelSessionTokenResponse'] = _CANCELSESSIONTOKENRESPONSE
DESCRIPTOR.message_types_by_name['GetAccessTokenRequest'] = _GETACCESSTOKENREQUEST
DESCRIPTOR.message_types_by_name['GetAccessTokenResponse'] = _GETACCESSTOKENRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSessionTokenRequest = _reflection.GeneratedProtocolMessageType('GetSessionTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSESSIONTOKENREQUEST,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.GetSessionTokenRequest)
  ))
_sym_db.RegisterMessage(GetSessionTokenRequest)

GetSessionTokenResponse = _reflection.GeneratedProtocolMessageType('GetSessionTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSESSIONTOKENRESPONSE,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.GetSessionTokenResponse)
  ))
_sym_db.RegisterMessage(GetSessionTokenResponse)

RenewSessionTokenRequest = _reflection.GeneratedProtocolMessageType('RenewSessionTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _RENEWSESSIONTOKENREQUEST,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.RenewSessionTokenRequest)
  ))
_sym_db.RegisterMessage(RenewSessionTokenRequest)

RenewSessionTokenResponse = _reflection.GeneratedProtocolMessageType('RenewSessionTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _RENEWSESSIONTOKENRESPONSE,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.RenewSessionTokenResponse)
  ))
_sym_db.RegisterMessage(RenewSessionTokenResponse)

CancelSessionTokenRequest = _reflection.GeneratedProtocolMessageType('CancelSessionTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _CANCELSESSIONTOKENREQUEST,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.CancelSessionTokenRequest)
  ))
_sym_db.RegisterMessage(CancelSessionTokenRequest)

CancelSessionTokenResponse = _reflection.GeneratedProtocolMessageType('CancelSessionTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _CANCELSESSIONTOKENRESPONSE,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.CancelSessionTokenResponse)
  ))
_sym_db.RegisterMessage(CancelSessionTokenResponse)

GetAccessTokenRequest = _reflection.GeneratedProtocolMessageType('GetAccessTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETACCESSTOKENREQUEST,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.GetAccessTokenRequest)
  ))
_sym_db.RegisterMessage(GetAccessTokenRequest)

GetAccessTokenResponse = _reflection.GeneratedProtocolMessageType('GetAccessTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETACCESSTOKENRESPONSE,
  __module__ = 'brokerservice.protobuf.broker_pb2'
  # @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.GetAccessTokenResponse)
  ))
_sym_db.RegisterMessage(GetAccessTokenResponse)


DESCRIPTOR._options = None

_BROKER = _descriptor.ServiceDescriptor(
  name='Broker',
  full_name='com.google.cloud.broker.protobuf.Broker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=534,
  serialized_end=1110,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSessionToken',
    full_name='com.google.cloud.broker.protobuf.Broker.GetSessionToken',
    index=0,
    containing_service=None,
    input_type=_GETSESSIONTOKENREQUEST,
    output_type=_GETSESSIONTOKENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RenewSessionToken',
    full_name='com.google.cloud.broker.protobuf.Broker.RenewSessionToken',
    index=1,
    containing_service=None,
    input_type=_RENEWSESSIONTOKENREQUEST,
    output_type=_RENEWSESSIONTOKENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CancelSessionToken',
    full_name='com.google.cloud.broker.protobuf.Broker.CancelSessionToken',
    index=2,
    containing_service=None,
    input_type=_CANCELSESSIONTOKENREQUEST,
    output_type=_CANCELSESSIONTOKENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccessToken',
    full_name='com.google.cloud.broker.protobuf.Broker.GetAccessToken',
    index=3,
    containing_service=None,
    input_type=_GETACCESSTOKENREQUEST,
    output_type=_GETACCESSTOKENRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROKER)

DESCRIPTOR.services_by_name['Broker'] = _BROKER

# @@protoc_insertion_point(module_scope)
