# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from brokerservice.protobuf import broker_pb2 as brokerservice_dot_protobuf_dot_broker__pb2


class BrokerStub(object):
  """Broker service -----------------------------------------

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSessionToken = channel.unary_unary(
        '/com.google.cloud.broker.protobuf.Broker/GetSessionToken',
        request_serializer=brokerservice_dot_protobuf_dot_broker__pb2.GetSessionTokenRequest.SerializeToString,
        response_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.GetSessionTokenResponse.FromString,
        )
    self.RenewSessionToken = channel.unary_unary(
        '/com.google.cloud.broker.protobuf.Broker/RenewSessionToken',
        request_serializer=brokerservice_dot_protobuf_dot_broker__pb2.RenewSessionTokenRequest.SerializeToString,
        response_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.RenewSessionTokenResponse.FromString,
        )
    self.CancelSessionToken = channel.unary_unary(
        '/com.google.cloud.broker.protobuf.Broker/CancelSessionToken',
        request_serializer=brokerservice_dot_protobuf_dot_broker__pb2.CancelSessionTokenRequest.SerializeToString,
        response_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.CancelSessionTokenResponse.FromString,
        )
    self.GetAccessToken = channel.unary_unary(
        '/com.google.cloud.broker.protobuf.Broker/GetAccessToken',
        request_serializer=brokerservice_dot_protobuf_dot_broker__pb2.GetAccessTokenRequest.SerializeToString,
        response_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.GetAccessTokenResponse.FromString,
        )


class BrokerServicer(object):
  """Broker service -----------------------------------------

  """

  def GetSessionToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RenewSessionToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelSessionToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccessToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BrokerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSessionToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessionToken,
          request_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.GetSessionTokenRequest.FromString,
          response_serializer=brokerservice_dot_protobuf_dot_broker__pb2.GetSessionTokenResponse.SerializeToString,
      ),
      'RenewSessionToken': grpc.unary_unary_rpc_method_handler(
          servicer.RenewSessionToken,
          request_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.RenewSessionTokenRequest.FromString,
          response_serializer=brokerservice_dot_protobuf_dot_broker__pb2.RenewSessionTokenResponse.SerializeToString,
      ),
      'CancelSessionToken': grpc.unary_unary_rpc_method_handler(
          servicer.CancelSessionToken,
          request_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.CancelSessionTokenRequest.FromString,
          response_serializer=brokerservice_dot_protobuf_dot_broker__pb2.CancelSessionTokenResponse.SerializeToString,
      ),
      'GetAccessToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccessToken,
          request_deserializer=brokerservice_dot_protobuf_dot_broker__pb2.GetAccessTokenRequest.FromString,
          response_serializer=brokerservice_dot_protobuf_dot_broker__pb2.GetAccessTokenResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.google.cloud.broker.protobuf.Broker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
