// Copyright 2019 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.cloud.broker.apps.brokerserver.endpoints;

import io.grpc.Status;
import io.grpc.stub.StreamObserver;
import org.slf4j.MDC;

import com.google.cloud.broker.apps.brokerserver.logging.LoggingUtils;
import com.google.cloud.broker.apps.brokerserver.validation.Validation;
import com.google.cloud.broker.apps.brokerserver.sessions.SessionAuthenticator;
import com.google.cloud.broker.authentication.backends.AbstractAuthenticationBackend;
import com.google.cloud.broker.apps.brokerserver.sessions.Session;
import com.google.cloud.broker.apps.brokerserver.accesstokens.AccessToken;
import com.google.cloud.broker.apps.brokerserver.accesstokens.AccessTokenCacheFetcher;

// Classes dynamically generated by protobuf-maven-plugin:
import com.google.cloud.broker.apps.brokerserver.protobuf.GetAccessTokenRequest;
import com.google.cloud.broker.apps.brokerserver.protobuf.GetAccessTokenResponse;


public class GetAccessToken {

    public static void run(GetAccessTokenRequest request, StreamObserver<GetAccessTokenResponse> responseObserver) {
        Validation.validateParameterNotEmpty("owner", request.getOwner());
        Validation.validateParameterNotEmpty("scopes", request.getScopesList());
        Validation.validateParameterNotEmpty("target", request.getTarget());

        // First try to authenticate the session, if any.
        SessionAuthenticator sessionAuthenticator = new SessionAuthenticator();
        Session session = sessionAuthenticator.authenticateSession();

        if (session == null) {
            // No session token was provided. The client is using direct authentication.
            // So let's authenticate the user.
            AbstractAuthenticationBackend authenticator = AbstractAuthenticationBackend.getInstance();
            String authenticatedUser = authenticator.authenticateUser();

            Validation.validateImpersonator(authenticatedUser, request.getOwner());
        }
        else {
            // A session token was provided. The client is using delegated authentication.
            Validation.validateScopes(request.getScopesList());
            if (!request.getTarget().equals(session.getTarget())) {
                throw Status.PERMISSION_DENIED
                    .withDescription("Target mismatch")
                    .asRuntimeException();
            }
            if (!request.getScopesList().equals(session.getScopes())) {
                throw Status.PERMISSION_DENIED
                    .withDescription("Scopes mismatch")
                    .asRuntimeException();
            }
            String sessionOwner = session.getOwner();
            String sessionOwnerUsername = sessionOwner.split("@")[0];
            if (!request.getOwner().equals(sessionOwner) && !request.getOwner().equals(sessionOwnerUsername)) {
                throw Status.PERMISSION_DENIED
                    .withDescription("Owner mismatch")
                    .asRuntimeException();
            }
        }

        AccessToken accessToken = (AccessToken) new AccessTokenCacheFetcher(
            request.getOwner(), request.getScopesList()).fetch();

        // Log success message
        MDC.put("owner", request.getOwner());
        MDC.put("scopes", String.join(",", request.getScopesList()));
        MDC.put("target", request.getTarget());
        if (session == null) {
            MDC.put("auth_mode", "direct");
        }
        else {
            MDC.put("auth_mode", "delegated");
            MDC.put("session_id", session.getId());
        }
        LoggingUtils.logSuccess(GetAccessToken.class.getSimpleName());

        // Return the response
        GetAccessTokenResponse response = GetAccessTokenResponse.newBuilder()
            .setAccessToken(accessToken.getValue())
            .setExpiresAt(accessToken.getExpiresAt())
            .build();
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

}
